### ISSUE TITLE
License configuration

### ISSUE THREAD

**Issue by babbush** [aspuru-guzik-group/qtorch#1]
I'd like to take your code for a spin but I don't think you have the license configured properly. I'm not an expert; maybe just typing "Apache 2" in the README as you've done is enough, but it is certainly not the standard way to license a GitHub repo. To configure things in the usual way: go to the repo and click "create new file". Then, where it says "name your file" start to type in "LICENSE". As you do that, a button should magically appear on the right that says "choose license template". Click that and then select Apache 2. Then click "Review and Submit" and make the pull request however you like. Once the LICENSE file is added to master, "Apache 2" should appear on the repo.

**Comment by schuylerfried** [comment]
Added!

**Comment by babbush** [comment]
:+1:
