### ISSUE TITLE
larger sample circuits for benchmarking

### ISSUE THREAD

**Issue by jcmgray** [aspuru-guzik-group/qtorch#5]
This looks like a great project and this is not really an 'issue'! I was just wondering if you had any larger circuit samples of ``.qasm`` files of (e.g. QAOA algorithms) to benchmark with? 

I have my own tensor network library (see circuit ``qasm`` example I've just added [here](https://quimb.readthedocs.io/en/develop/examples/ex_quantum_circuit.html)) which uses [opt_einsum](https://github.com/dgasmith/opt_einsum) to perform the contractions.

``opt_einsum`` just uses a greedy approach that is much less sophisticated than e.g. treewidth based approaches for finding optimal paths. It has however, worked pretty well so far, so I would be interested in comparing at what point (number of qubits or graph-connectedness) it falls behind!

**Comment by schuylerfried** [comment]
Hi @jcmgray, 

I like your tensor network visualization a lot! The opt_einsum method may be similar to the greedy `stochastic` approach we wrote for this library, and you might be interested in reading our paper https://arxiv.org/abs/1709.03636, which has comparisons between the `stochastic` method and the treewidth approximation algorithm (I wonder if you'll have similar results). 

We do have some QAOA algorithm circuits to benchmark with - these are located in the Samples folder - they have strange names like `4regRand30Node...qasm`. All of these files implement QAOA maxcut with a single trotterization step (p=1). If you want to generate your own QAOA maxcut qasm files, you can first use the XRegGraphGen (within the main directory of this package) to generate x-regular (meaning you can specify the regularity), random, simply-connected, graph .dgf files, which you then pass as input to a compiled maxcut binary (compiled by running `make cut` from the main directory. If you don't actually want to run the tensor network contractions (and just want the qasm file), you can put an `exit(0)` call on line 274 of `maxcut.cpp` before compiling it. Please let me know if you have any more questions

Cheers,

Eric Fried

**Comment by jcmgray** [comment]
> I like your tensor network visualization a lot!

Thanks, yeah it is very helpful when creating/debugging TN code!

> The opt_einsum method may be similar to the greedy stochastic approach we wrote for this library, and you might be interested in reading our paper https://arxiv.org/abs/1709.03636, which has comparisons between the stochastic method and the treewidth approximation algorithm (I wonder if you'll have similar results).

Indeed, your paper brought me here. The greedy method is definitely similar, but rather than rank you calculate the total size/memory removed, and always choose the best edge (or one of). To be honest I don't really have a good intuition regarding whether the randomness helps or not so it would be an interesting test. 

And thanks very much for the detailed instructions about generating the `.qasm` files, I shall give that a go at some point soon hopefully.

**Comment by jcmgray** [comment]
I couldn't quite get the ``qasm`` generation to work - when I run ``maxcutQAOA`` (with or without an ``exit`` call, and regardless of the number of nodes in the graph) I just get these lines repeated:

```
...
Parsing nodes from file....
Creating Z measurement on qubit: 0
Creating Z measurement on qubit: 1
Tracing out qubit: 2
Tracing out qubit: 3
Tracing out qubit: 4
Tracing out qubit: 5
Creating qubit 0 in the initial state: |0><0|
Creating qubit 1 in the initial state: |0><0|
Creating qubit 2 in the initial state: |0><0|
Creating qubit 3 in the initial state: |0><0|
Creating qubit 4 in the initial state: |0><0|
Parsing nodes from file....
...
```

[N.B. I had to ``#include`` ``<memory>`` and ``<algorithm>`` in the graph generator source and change the header comments style from python to c.]

Anyway I wrote a quick python script to generate these files using ``networkx`` instead, which may be of use, it's [in this gist here](https://gist.github.com/jcmgray/79f7c779c85f80ee6e72c1e7a042e0f5).

One final question, in the paper, is the 'single contraction' that is benchmarked:
- ``Tr ( |0><0| |psi><psi| )`` ( as would be used in the most likely string estimation)
- Or something more complex like ``<psi| H_maxcut |psi>`` ?

where ``|psi>`` is the state resulting from applying the ``p=1`` unitary circuit in the qasm files.

**Comment by schuylerfried** [comment]
@jcmgray,

Sorry for the delayed response - I've been working on other projects recently. Thanks for the heads up about the graph generator - I'll fix it. Re QASM generation: let me see if I can split the QAOA circuit creation into a different function (should make things easier I hope). I think what you're seeing is the best angle calculation. For a p=1 circuit on a 3-regular graph, computing the expectation value for H_maxcut takes at most 6 qubits, no matter how many nodes in the graph! The original QAOA paper (section V.) should provide an explanation: https://arxiv.org/abs/1411.4028. Was the circuit you were running 3-regular with a single p step? I should clarify that We never actually generate the entire H_maxcut circuit until we've calculated the optimal angles and are estimating the most-likely string.

The python script is great! I'm sure C++ has similar graph libraries, but I overlooked that when I first wrote this library. 

Re. final question: The single contraction that's bench-marked is the most-likely string estimation, given maximized angles to prepare |psi>.

**Comment by schuylerfried** [comment]
Fixed the compilation errors!

**Comment by jcmgray** [comment]
Thanks for the update and fix! I'll give it a go.

And I think I see what you mean regarding the expectation of ``H_maxcut`` now - each of the clauses can be computed independently as essentially a local term (with locality depending on ``p``).

In the end I also discovered these circuits which you maybe already know: https://github.com/sboixo/GRCS. My updated ['circuit example'](https://quimb.readthedocs.io/en/latest/examples/ex_quantum_circuit.html) now uses one of these.
